/**
 * cabinet.ts — Cabinet Council: CM and Ministers with official portfolios.
 *
 * HOW TO UPDATE:
 *   - When a minister is added: append a new CabinetMinister entry at the bottom.
 *   - When portfolios change: update the `depts` array and `title` of the minister.
 *   - When a minister is removed: delete their entry from the array.
 *   - id format: YYYYMMDD### (date of appointment / portfolio change)
 *   - colorClass cycles: "color-a" | "color-b" | "color-c" | "color-d"
 *   - variant: "highlight" triggers a special saffron visual treatment in the UI.
 *     Use for notable appointments (e.g. first woman minister, youngest minister).
 */

export interface CabinetCM {
  name: string;
  constituency: string;
  party: string;
  portfolios: string[];      // List of CM-held departments
  photoPath: string;         // Path relative to /public e.g. "/Honble CM photo.jpg"
  approvedDate: string;      // "May 16, 2026"
  approvedSource: string;    // "Source: Lok Bhavan Press Release"
}

export interface CabinetMinister {
  id: number;                                           // YYYYMMDD###
  initials: string;                                     // 2-letter initials e.g. "NA"
  colorClass: 'color-a' | 'color-b' | 'color-c' | 'color-d';
  name: string;
  constituency: string;
  title: string;                                        // Portfolio headline
  depts: string[];                                      // Department tag labels
  bio: string;
  note?: string;                                        // e.g. "Only Woman Minister"
  variant?: 'highlight';                                // Triggers saffron accent UI
}

export const cabinetCM: CabinetCM = {
  name: "C. Joseph Vijay",
  constituency: "Perambur",
  party: "TVK",
  portfolios: [
    "Home & Police",
    "Public Administration",
    "General Administration",
    "Special Programme Implementation",
    "Special Initiatives",
    "Poverty Alleviation & Rural Indebtedness",
    "Youth Welfare",
    "Children, Elderly & Differently Abled",
    "Municipal Administration",
    "Urban & Rural Water Supply",
    "IAS · IPS · IFS Services",
  ],
  photoPath: "/Honble CM photo.jpg",
  approvedDate: "May 21, 2026",
  approvedSource: "Source: Lok Bhavan Press Release",
};

export const cabinetMinisters: CabinetMinister[] = [
  {
    id: 20260516001,
    initials: "NA",
    colorClass: "color-a",
    name: "N. Anand",
    constituency: "T. Nagar",
    title: "Rural Development & Water Resources",
    depts: ["Rural Dev", "Panchayats", "Irrigation"],
    bio: "Vijay's closest aide, Bussy Anand led Vijay Rasigar Mandram in Puducherry. TVK General Secretary & founding office-bearer.",
  },
  {
    id: 20260516002,
    initials: "AA",
    colorClass: "color-b",
    name: "Aadhav Arjuna",
    constituency: "Villivakkam",
    title: "Public Works & Sports Development",
    depts: ["PWD", "Highways", "Minor Ports", "Sports"],
    bio: "Basketball Federation of India President. Political consultant and former VCK deputy general secretary. Son-in-law of lottery businessman Santiago Martin.",
  },
  {
    id: 20260516003,
    initials: "KA",
    colorClass: "color-c",
    name: "KG Arunraj",
    constituency: "Tiruchengodu",
    title: "Health, Medical Education & Family Welfare",
    depts: ["Health", "Medical Education", "Family Welfare"],
    bio: "Former IRS officer & MBBS doctor. Voluntarily retired from Income Tax Dept. TVK General Secretary for Propaganda & Policy.",
  },
  {
    id: 20260521004,
    initials: "KS",
    colorClass: "color-d",
    name: "KA Sengottaiyan",
    constituency: "Gobichettipalayam",
    title: "Revenue & Disaster Management",
    depts: ["Revenue", "Disaster Management", "Bhoodan", "Legislative Assembly"],
    bio: "78-year-old veteran, 10-time MLA. Former School Education & Transport Minister under Jayalalithaa. Portfolio revised from Finance on May 21.",
  },
  {
    id: 20260516005,
    initials: "PV",
    colorClass: "color-a",
    name: "P. Venkataramanan",
    constituency: "Mylapore",
    title: "Food, Civil Supplies & Consumer Affairs",
    depts: ["Food", "Civil Supplies", "Consumer Affairs"],
    bio: "TVK Party Treasurer. Won Mylapore with 70,070 votes. Post-graduate, no criminal cases declared. Assets ₹5.4 crore.",
  },
  {
    id: 20260516006,
    initials: "CN",
    colorClass: "color-b",
    name: "C.T.R. Nirmalkumar",
    constituency: "Thirupparankundram",
    title: "Energy Resources & Law",
    depts: ["Electricity", "Non-Conventional Energy", "Law", "Prisons", "Elections"],
    bio: "Former TN BJP IT Wing State President. Holds degrees in Engineering, Law, and Criminology. TVK Joint General Secretary & key spokesperson.",
  },
  {
    id: 20260516007,
    initials: "RA",
    colorClass: "color-c",
    name: "Rajmohan A.",
    constituency: "Egmore",
    title: "School Education, Tamil Dev & Information",
    depts: ["School Education", "Tamil Dev", "Info & Publicity", "Archaeology", "Film Tech"],
    bio: "Media figure, emerged from Put Chutney YouTube platform. Played key role in TVK's millennial & Gen Z digital outreach.",
  },
  {
    id: 20260516008,
    initials: "TK",
    colorClass: "color-d",
    name: "TK Prabhu",
    constituency: "Karaikudi",
    title: "Natural Resources & Minerals",
    depts: ["Natural Resources", "Minerals & Mines"],
    bio: "Dentist by profession. Assets ₹11.4 crore. Annual income ₹54.6 lakh declared. No pending criminal cases.",
  },
  {
    id: 20260516009,
    initials: "SK",
    colorClass: "color-a",
    name: "S. Keerthana",
    constituency: "Sivakasi",
    title: "Industries & Investment Promotion",
    depts: ["Industries", "Investment Promotion"],
    bio: "M.Sc Statistics. Defeated sitting Congress MLA by 11,000+ votes. One of youngest female cabinet members in TN history. Assets ₹22.6 lakh.",
    note: "Women Minister",
  },
  {
    id: 20260521001,
    initials: "AS",
    colorClass: "color-b",
    name: "A. Srinath",
    constituency: "Thoothukudi",
    title: "Fisheries & Fishermen Welfare",
    depts: ["Fisheries", "Fisheries Dev Corp"],
    bio: "Long-time friend of CM Vijay. Began film career alongside Vijay in Naalaiya Theerpu (1992). Defeated former DMK Minister P. Geetha Jeevan.",
  },
  {
    id: 20260521002,
    initials: "SK",
    colorClass: "color-c",
    name: "S. Kamali",
    constituency: "Avinashi",
    title: "Animal Husbandry",
    depts: ["Animal Husbandry"],
    bio: "28-year-old homemaker with MA in English Literature and B.Ed. Defeated Union MoS L. Murugan. One of youngest ministers in the cabinet.",
    note: "Women Minister",
  },
  {
    id: 20260521003,
    initials: "CV",
    colorClass: "color-d",
    name: "C. Vijayalakshmi",
    constituency: "Kumarapalayam",
    title: "Milk & Dairy Development",
    depts: ["Dairy Development"],
    bio: "Frontline TVK leader. Defeated AIADMK strongman and former Minister P. Thangamani. Self-employed, studied to Class 12.",
    note: "Women Minister",
  },
  {
    id: 20260521005,
    initials: "RR",
    colorClass: "color-a",
    name: "R.V. Ranjithkumar",
    constituency: "Kancheepuram",
    title: "Forests",
    depts: ["Forests"],
    bio: "50-year-old involved in farming, business, and real estate. Holds a BA degree from Tamil Nadu Open University.",
  },
  {
    id: 20260521006,
    initials: "RV",
    colorClass: "color-b",
    name: "R. Vinoth",
    constituency: "Kumbakonam",
    title: "Agriculture & Farmers Welfare",
    depts: ["Agriculture", "Horticulture", "Sugar", "Wasteland Dev"],
    bio: "32-year-old involved in trading. Discontinued B.E. degree. Represents Kumbakonam in Thanjavur district.",
  },
  {
    id: 20260521007,
    initials: "VR",
    colorClass: "color-c",
    name: "V.K. Rajeev",
    constituency: "Thiruvadanai",
    title: "Environment & Climate Change",
    depts: ["Environment", "Pollution Control", "Climate Change"],
    bio: "33-year-old doctor (MBBS, Raja Muthiah Medical College, 2016). Sole TVK MLA from Ramanathapuram district.",
  },
  {
    id: 20260521008,
    initials: "BR",
    colorClass: "color-d",
    name: "B. Rajkumar",
    constituency: "Cuddalore",
    title: "Housing & Urban Development",
    depts: ["Housing", "Rural Housing", "Town Planning", "CMDA", "Urban Dev"],
    bio: "46-year-old in real estate and business. Diploma in Mechanical Engineering from Muthiah Polytechnic, Chidambaram.",
  },
  {
    id: 20260521009,
    initials: "VG",
    colorClass: "color-a",
    name: "V. Gandhiraj",
    constituency: "Arakkonam",
    title: "Co-operation",
    depts: ["Co-operation"],
    bio: "52-year-old civil contractor. Won AIADMK stronghold of Arakkonam. Discontinued BA from University of Madras.",
  },
  {
    id: 20260521010,
    initials: "PM",
    colorClass: "color-b",
    name: "P. Mathan Raja",
    constituency: "Ottapidaram",
    title: "Micro, Small & Medium Enterprises",
    depts: ["MSME", "Rural Industries", "Cottage Industries"],
    bio: "41-year-old businessman with B.E. from Sri Venkateswara College of Engineering. Elected from Thoothukudi district.",
  },
  {
    id: 20260521011,
    initials: "KJ",
    colorClass: "color-c",
    name: "K. Jegadeshwari",
    constituency: "Rajapalayam",
    title: "Social Welfare & Women Empowerment",
    depts: ["Social Welfare", "Women Welfare", "Nutritious Meal Programme", "Correctional Admin"],
    bio: "40-year-old B.Sc holder from Virudhunagar district. Takes over Women Welfare portfolios previously held by CM Vijay.",
    note: "Women Minister",
  },
  {
    id: 20260521012,
    initials: "SR",
    colorClass: "color-d",
    name: "S. Rajesh Kumar",
    constituency: "Killiyoor",
    title: "Tourism",
    depts: ["Tourism", "Tourism Dev Corp"],
    bio: "Senior Congress leader elected for 3rd consecutive term from Kanniyakumari district. Congress returns to TN government after 59 years.",
  },
  {
    id: 20260521013,
    initials: "MV",
    colorClass: "color-a",
    name: "M. Vijay Balaji",
    constituency: "Erode East",
    title: "Handlooms, Textiles & Khadi",
    depts: ["Handlooms", "Textiles", "Khadi & Village Industries"],
    bio: "39-year-old businessman with B.Com degree. Erode East constituency saw two by-elections during the previous Assembly tenure.",
  },
  {
    id: 20260521014,
    initials: "DL",
    colorClass: "color-b",
    name: "D. Lokesh Tamilselvan",
    constituency: "Rasipuram",
    title: "Commercial Taxes & Registration",
    depts: ["Commercial Taxes", "Registration", "Stamp Act", "Chits"],
    bio: "Son of former TN Assembly Speaker P. Dhanapal. Defeated former DMK Minister M. Mathivendhan in Namakkal district.",
  },
  {
    id: 20260521015,
    initials: "AV",
    colorClass: "color-c",
    name: "A. Vijay Tamilan Parthiban",
    constituency: "Salem South",
    title: "Transport",
    depts: ["Transport", "Motor Vehicles", "Nationalised Transport"],
    bio: "Elected from Salem South constituency. Oversees motor vehicle administration and state transport corporations.",
  },
  {
    id: 20260521016,
    initials: "SR",
    colorClass: "color-d",
    name: "S. Ramesh",
    constituency: "Srirangam",
    title: "Hindu Religious & Charitable Endowments",
    depts: ["Hindu Religious", "Charitable Endowments"],
    bio: "31-year-old B.E. holder. State coordinator of TVK media wing, known for articulate public speaking. Elected from Tiruchi district.",
  },
  {
    id: 20260521017,
    initials: "PV",
    colorClass: "color-a",
    name: "P. Viswanathan",
    constituency: "Melur",
    title: "Higher Education",
    depts: ["Higher Education", "Technical Education", "Electronics", "Science & Technology"],
    bio: "Congress MLA from Madurai district. Final Congress candidate announced before 2026 election. Hails from Thazhambur in Chengalpattu.",
  },
  {
    id: 20260521018,
    initials: "RK",
    colorClass: "color-b",
    name: "R. Kumar",
    constituency: "Velachery",
    title: "Artificial Intelligence & Information Technology",
    depts: ["AI", "IT & Digital Services"],
    bio: "60-year-old landlord and businessman. B.E. from Madras University, completed Business Leadership Programme at IIM Bangalore.",
    note: "First AI Minister",
    variant: "highlight",
  },
  {
    id: 20260521019,
    initials: "KT",
    colorClass: "color-c",
    name: "K. Thennarasu",
    constituency: "Sriperumbudur",
    title: "Non-Resident Tamils Welfare",
    depts: ["NRT Welfare", "Refugees & Evacuees"],
    bio: "Defeated TNCC president K. Selvaperunthagai in 2026 election. Studied to Class 10 and works as a commission agent.",
  },
  {
    id: 20260521020,
    initials: "VS",
    colorClass: "color-d",
    name: "V. Sampathkumar",
    constituency: "Coimbatore North",
    title: "Backward Classes Welfare",
    depts: ["BC Welfare", "MBC Welfare", "Denotified Communities"],
    bio: "47-year-old businessman with MBA from Annamalai University. Defeated BJP Mahila Morcha national president Vanathi Srinivasan.",
  },
  {
    id: 20260521021,
    initials: "JM",
    colorClass: "color-a",
    name: "J. Mohamed Farvas",
    constituency: "Aranthangi",
    title: "Labour Welfare & Skill Development",
    depts: ["Labour Welfare", "Employment & Training", "Weights & Measures", "Bonded Labour"],
    bio: "31-year-old in printing business with BA LLB (Hons.) from a National Law School. Former Pudukkottai Corporation councillor.",
  },
  {
    id: 20260521022,
    initials: "DS",
    colorClass: "color-b",
    name: "D. Sarathkumar",
    constituency: "Tambaram",
    title: "Human Resources Management",
    depts: ["Human Resources Management", "Ex-Servicemen Welfare"],
    bio: "34-year-old civil contractor with BBA from M.M. Jain College, Meenambakkam. Elected from Chengalpattu district.",
  },
  {
    id: 20260521023,
    initials: "NM",
    colorClass: "color-c",
    name: "N. Marie Wilson",
    constituency: "Dr. Radhakrishnan Nagar",
    title: "Finance, Planning & Development",
    depts: ["Finance", "Pensions", "Planning & Development"],
    bio: "46-year-old with Doctorate in Management Science from JNT University, Hyderabad. Part of leading private educational institution in Chennai.",
  },
  {
    id: 20260521024,
    initials: "KV",
    colorClass: "color-d",
    name: "K. Vignesh",
    constituency: "Kinathukadavu",
    title: "Prohibition & Excise",
    depts: ["Prohibition", "Excise"],
    bio: "38-year-old businessman with B.Computer Science degree. Won traditional AIADMK stronghold of Kinathukadavu in Coimbatore district.",
  },
];
